# check-status.yml
---
  - hosts: webservers:loadbalancers
    become: true
    tasks:
      - name: Check status of Apache
        command: service httpd status
        args:
          warn: no #dont warn us about using the CMD command rather than service CMD
        changed_when: false #dont report changes, flag them as 0

      - name: This will not fail
        command: /bin/false
        ignore_errors: yes