---
  - hosts: webservers
    become: true

    vars:
      path_to_app: "/var/www/html"

    tasks: 
      - copy:
          src: ./index.php
          dest: "{{ path_to_app }}" #/var/www/html
          mode: 0755
      
      - name: Create simple info page 
        copy:
          dest: "{{ path_to_app }}/info.php"
          content: "<h1> Info about our webserver {{ ansible_hostname }} </h1>"

      - name: See directory contents
        command: ls -la {{ path_to_app }}
        register: dir_contents #saves the output and registers on the specified var.

      - name: debug directory contents
        debug:
          msg: "{{ dir_contents }}"

      - name: Configure php.ini file
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=On'
        notify: Restart Apache
    
    handlers:
      - name: Restart Apache
        service: name=httpd state=restarted